# Generated by Django 6.0.3 on 2026-04-07 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ubicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=25)),
                ('direccion', models.CharField(max_length=85)),
                ('referencia', models.CharField(max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ubicacion.ciudad')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ubicacion.departamento')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ubicacion.pais')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ubicacion.provincia')),
            ],
        ),
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('principal', 'Principal'), ('secundario', 'Secundario'), ('transito', 'Tránsito'), ('cuarentena', 'Cuarentena')], default='principal', max_length=15)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sucursales.sucursal')),
            ],
        ),
    ]
