# Generated by Django 6.0.3 on 2026-06-03 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0002_almacen_actualizado_por_almacen_creado_por_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='almacen',
            options={'verbose_name': 'Almacén', 'verbose_name_plural': 'Almacenes'},
        ),
        migrations.AlterModelOptions(
            name='sucursal',
            options={'verbose_name': 'Sucursal', 'verbose_name_plural': 'Sucursales'},
        ),
    ]
