# Generated by Django 6.0.3 on 2026-06-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0003_alter_almacen_options_alter_sucursal_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacen',
            name='capacidad',
            field=models.IntegerField(default=1000, help_text='Capacidad máxima en unidades'),
        ),
    ]
