# Generated by Django 6.0.3 on 2026-06-28 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_movimiento_actualizado_por_movimiento_creado_por_and_more'),
        ('sucursales', '0003_alter_almacen_options_alter_sucursal_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallemovimiento',
            options={'verbose_name': 'Detalle de Movimiento', 'verbose_name_plural': 'Detalles de Movimientos'},
        ),
        migrations.AlterModelOptions(
            name='inventario',
            options={'verbose_name': 'Inventario', 'verbose_name_plural': 'Inventarios'},
        ),
        migrations.AlterModelOptions(
            name='movimiento',
            options={'verbose_name': 'Movimiento', 'verbose_name_plural': 'Movimientos'},
        ),
        migrations.AddField(
            model_name='movimiento',
            name='almacen_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_destino', to='sucursales.almacen'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='almacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_origen', to='sucursales.almacen'),
        ),
    ]
