# Generated by Django 6.0.3 on 2026-04-07 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        ('productos', '0001_initial'),
        ('ubicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.lote'),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ubicacion.ciudad'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ubicacion.departamento'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ubicacion.pais'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ubicacion.provincia'),
        ),
        migrations.AddField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compras.proveedor'),
        ),
    ]
