# Generated by Django 6.0.3 on 2026-04-07 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0002_tipos_permiso_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipopermiso',
            name='codigo',
            field=models.SlugField(help_text="Clave interna, p.ej. 'ver_reportes'", max_length=80, unique=True),
        ),
    ]
