# Generated by Django 6.0.3 on 2026-05-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0003_modulo_activo_to_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='grupo_menu',
            field=models.CharField(blank=True, help_text="Título de sección en el sidebar, p.ej. 'Ventas', 'Configuración'", max_length=80),
        ),
    ]
